apiVersion: v1
kind: Secret

metadata:
  name: db-connection

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU18yc0lTSG9iVmJkTlNMWHpnME40QG5sdy11bml0ZS1kby11c2VyLTgxMjQ0OTctMC5jLmRiLm9uZGlnaXRhbG9jZWFuLmNvbToyNTA2MC9ubHctdW5pdGU/c3NsbW9kZT1yZXF1aXJlCg==